name: Test Secrets

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check Region
        run: |
          if [ -z "${{ secrets.AWS_REGION }}" ]; then
            echo "AWS_REGION is EMPTY"
          else
            echo "AWS_REGION exists"
          fi
